### ISSUE TITLE
custom lzss format

### ISSUE THREAD

**Issue by Mcrtin** [dfgordon/retrocompressor#3]
I'm currently writing a tool for decrypting and encrypting assets for The Settlers II 10th Anniversary (https://github.com/S2-modders/S2-10th-Anniversary-decrypter)
They unfortunately have a custom lzss format for compression. It basically boils down to this:
```rust
comp.push(copy_offset as u8);
comp.push((copy_offset >> 4) as u8 & 0x30 | copy_len as u8 - 3);
```
(copy_offset is the offset into the 1024-byte ring buffer and copy_len is the length of the matching bytes (max 18))
Is this crate able to support that?

**Comment by dfgordon** [comment]
Basically no, because Huffman coding is baked in. Developing a more general LZSS module is on the to-do list.
